_target_: nemo.collections.multimodal.modules.nerf.guidance.stablediffusion_trt_pipeline.StableDiffusion
checkpoint: /sd_checkpoints/nemo-1.5/sd-1.5.nemo
plan_dir: /sd_checkpoints/nemo-1.5/plan
sampler_type=: DDIM"
t_range: [0.02, 0.98]
