defaults:
  - _self_
  - optional tp_overlap@model.ub_tp_comm_overlap_cfg:

hydra:
  searchpath:
    - file:///opt/NeMo/examples/nlp/language_modeling/conf

run:
  name: sft_${.model_train_name}
  results_dir: ${base_results_dir}/${.name}
  time_limit: 04:00:00
  dependency: singleton
  convert_name: convert_nemo
  model_train_name: qwen2
  convert_dir: ${base_results_dir}/${.model_train_name}/${.convert_name}

trainer:
  devices: 8
  accelerator: gpu
  num_nodes: 1
  precision: bf16
  logger: False # logger provided by exp_manager
  enable_checkpointing: False
  use_distributed_sampler: False
  max_epochs: 9999
  max_steps: 20000 # consumed_samples = global_step * micro_batch_size * data_parallel_size * accumulate_grad_batches
  log_every_n_steps: 10 # frequency with which training steps are logged
  val_check_interval: 200 # If is an int n > 1, will run val every n training steps, if a float 0.0 - 1.0 will run val every epoch fraction, e.g. 0.25 will run val every quarter epoch
  gradient_clip_val: 1.0

exp_manager:
  explicit_log_dir: ${peft.run.results_dir}/results
  exp_dir: null
  name: ${peft.run.name}
  create_wandb_logger: False
  wandb_logger_kwargs:
    project: null
    name: null
  resume_if_exists: True
  resume_ignore_no_checkpoint: True
  create_checkpoint_callback: True
  checkpoint_callback_params:
    monitor: validation_${peft.model.data.validation_ds.metric.name}
    save_top_k: 1
    mode: min
    save_nemo_on_train_end: True
    filename: '${peft.exp_manager.name}--{${.monitor}:.3f}-{step}-{consumed_samples}'
    model_parallel_size: ${multiply:${peft.model.tensor_model_parallel_size}, ${peft.model.pipeline_model_parallel_size}}
    always_save_nemo: False
    save_best_model: True
  create_early_stopping_callback: True
  early_stopping_callback_params:
    monitor: "val_loss"
    mode: "min"
    min_delta: 0.001
    patience: 10
    verbose: True
    strict: False # Should be False to avoid a runtime error where EarlyStopping says monitor is unavailable, which sometimes happens with resumed training.
  create_tensorboard_logger: False
  log_global_rank_0_only: True

model:
  seed: 1234
  tensor_model_parallel_size: 1 # intra-layer model parallelism
  pipeline_model_parallel_size: 1 # inter-layer model parallelism
  virtual_pipeline_model_parallel_size: null

  encoder_seq_length: ${peft.model.data.train_ds.max_seq_length}

  global_batch_size: 128
  micro_batch_size: 4
  restore_from_path: ${peft.run.convert_dir}/results/megatron_qwen2.nemo # Path to an existing .nemo model you wish to add new tasks to or run inference with
  resume_from_checkpoint: null # The path to a checkpoint file to continue the training, restores the whole state including the epoch, step, LR schedulers, apex, etc.
  save_nemo_on_validation_end: False # Saves an inference ready .nemo file every time a checkpoint is saved during training.
  sync_batch_comm: False
  overlap_p2p_comm: False
  ub_tp_comm_overlap: False
  tp_comm_atomic_ag: False
  tp_comm_atomic_rs: False

  megatron_amp_O2: True
  mcore_gpt: True
  transformer_engine: False

  get_attention_mask_from_fusion: True
  apply_rope_fusion: True
  bias_activation_fusion: True
  bias_dropout_add_fusion: True
  masked_softmax_fusion: True
  gradient_accumulation_fusion: True
  grad_div_ar_fusion: True

  fp8: False
  fp8_e4m3: False
  fp8_hybrid: True
  fp8_margin: 0
  fp8_interval: 1
  fp8_amax_history_len: 512
  fp8_amax_compute_algo: max
  fp8_wgrad: True

  ## Sequence Parallelism
  # Makes tensor parallelism more memory efficient for LLMs (20B+) by parallelizing layer norms and dropout sequentially
  # See Reducing Activation Recomputation in Large Transformer Models: https://arxiv.org/abs/2205.05198 for more details.
  sequence_parallel: False

  ## Activation Checkpoint
  activations_checkpoint_granularity: null # 'selective' or 'full'
  activations_checkpoint_method: null # 'uniform', 'block', not used with 'selective'
  # 'uniform' divides the total number of transformer layers and checkpoints the input activation
  # of each chunk at the specified granularity
  # 'block' checkpoints the specified number of layers per pipeline stage at the specified granularity
  activations_checkpoint_num_layers: null # not used with 'selective'
  activations_checkpoint_layers_per_pipeline: null
  answer_only_loss: False
  gradient_as_bucket_view: True

  hidden_dropout: 0.0
  attention_dropout: 0.0
  ffn_dropout: 0.0

  peft:
    peft_scheme: null  # null (SFT, no PEFT), ptuning, lora
    restore_from_path: null

    # Used for adapter peft training
    adapter_tuning:
      type: 'parallel_adapter' # this should be either 'parallel_adapter' or 'linear_adapter'
      adapter_dim: 32
      adapter_dropout: 0.0
      norm_position: 'pre' # This can be set to 'pre', 'post' or null, 'pre' is normally what is used.
      column_init_method: 'xavier' # IGNORED if linear_adapter is used, options: xavier, zero or normal
      row_init_method: 'zero' # IGNORED if linear_adapter is used, options: xavier, zero or normal
      norm_type: 'mixedfusedlayernorm' # IGNORED if layer_adapter is used,  options are ['layernorm', 'mixedfusedlayernorm']
      layer_selection: null  # selects in which layers to add adapters, e.g. [1,12] will add adapters to layer 1 (lowest) and 12. null will apply adapters to all layers
      weight_tying: False
      position_embedding_strategy: null # used only when weight_tying is True

    lora_tuning:
      adapter_dim: 32
      adapter_dropout: 0.0
      column_init_method: 'xavier' # IGNORED if linear_adapter is used, options: xavier, zero or normal
      row_init_method: 'zero' # IGNORED if linear_adapter is used, options: xavier, zero or normal
      layer_selection:  null  # selects in which layers to add lora adapters. e.g. [1,12] will add lora to layer 1 (lowest) and 12. null will apply adapters to all layers
      weight_tying: False
      position_embedding_strategy: null # used only when weight_tying is True

    # Used for p-tuning peft training
    p_tuning:
      virtual_tokens: 10  # The number of virtual tokens the prompt encoder should add at the start of the sequence
      bottleneck_dim: 1024  # the size of the prompt encoder mlp bottleneck
      embedding_dim: 1024  # the size of the prompt encoder embeddings
      init_std: 0.023

    ia3_tuning:
      layer_selection:  null  # selects in which layers to add ia3 adapters. e.g. [1,12] will add lora to layer 1 (lowest) and 12. null will apply adapters to all layers

  data:
    train_ds:
      # Example of how to specify paths to multiple datasets
      # file_names:
      #   - /path/to/squad.jsonl
      #   - /path/to/mnli.jsonl
      #   - /path/to/boolq.jsonl
      # Example of how each dataset is formatted
      # {'input': 'John von Neumann\nVon Neumann made fundamental contributions .... Q: What did the math of artificial viscosity do?', 'output': 'smoothed the shock transition without sacrificing basic physics'}
      file_names: ??? # Path to a list of JSONL files corresponding to the source data.
      global_batch_size: ${peft.model.global_batch_size}
      micro_batch_size: ${peft.model.micro_batch_size}
      shuffle: True
      num_workers: 2
      memmap_workers: 2
      pin_memory: True
      packed_sequence: False # Set to true to load with GPTSFTPackedDataset
      pad_to_max_length: False
      max_seq_length: 2048
      min_seq_length: 1
      drop_last: True
      # Example of how to specify concat_sampling_probabilities
      # concat_sampling_probabilities:
      #   - 0.5
      #   - 0.25
      #   - 0.25
      concat_sampling_probabilities: null # When providing a list of datasets, this arg defines the sampling probabilities from each dataset when strategy='random'
      label_key: 'output'
      add_eos: True
      add_sep: False
      add_bos: False
      truncation_field: "input" # # Can be multiple keys separated with ',' Options: keys in prompt_template
      index_mapping_dir: null # Path to a directory to write index mapping files.
      prompt_template: "{input} {output}" # fstring to use for assistant prompt. Example: "Q: {input}\nA: {output}"
      truncation_method: 'right' # Truncation from which position, Options: ['left', 'right'] 
    validation_ds:
      file_names: ??? # Path to a list of JSONL files corresponding to the source data. Data format is identical to train_ds.
      names: null # Names of the corresponding datasets used to log metrics.
      global_batch_size: ${peft.model.global_batch_size}
      micro_batch_size: ${peft.model.micro_batch_size}
      shuffle: False
      num_workers: ${peft.model.data.train_ds.num_workers}
      memmap_workers: ${peft.model.data.train_ds.memmap_workers}
      pin_memory: True
      max_seq_length: ${peft.model.data.train_ds.max_seq_length}
      min_seq_length: ${peft.model.data.train_ds.min_seq_length}
      drop_last: False
      label_key: ${peft.model.data.train_ds.label_key}
      add_eos: ${peft.model.data.train_ds.add_eos}
      add_sep: ${peft.model.data.train_ds.add_sep}
      add_bos: ${peft.model.data.train_ds.add_bos}
      write_predictions_to_file: False
      output_file_path_prefix: null # Prefix of the file to write predictions to.
      truncation_field: ${peft.model.data.train_ds.truncation_field} # Options: keys in prompt_template
      index_mapping_dir: null # Path to a directory to write index mapping files.
      prompt_template: ${peft.model.data.train_ds.prompt_template} # fstring to use for assistant prompt. Example: "Q: {input}\nA: {output}"
      tokens_to_generate: 32 # decide how many tokens we want to generate to evaluate performance with string metrics
      truncation_method: 'right' # Truncation from which position, Options: ['left', 'right']
      metric:
        name: "loss" # Name of the evaluation metric to use. Options: ['exact_string_match', 'loss']
        average: null # Average the metric over the dataset. Options: ['macro', 'micro']. Works only for 'F1', 'accuracy' etc. Refer to torchmetrics for metrics where this is supported.
        num_classes: null
    test_ds:
      file_names: null # Path to a list of JSONL files corresponding to the source data. Data format is identical to train_ds.
      names: null # Names of the corresponding datasets used to log metrics.
      global_batch_size: ${peft.model.global_batch_size}
      micro_batch_size: ${peft.model.micro_batch_size}
      shuffle: False
      num_workers: ${peft.model.data.train_ds.num_workers}
      memmap_workers: ${peft.model.data.train_ds.memmap_workers}
      pin_memory: True
      max_seq_length: ${peft.model.data.train_ds.max_seq_length}
      min_seq_length: ${peft.model.data.train_ds.min_seq_length}
      drop_last: False
      label_key: ${peft.model.data.train_ds.label_key}
      add_eos: ${peft.model.data.train_ds.add_eos}
      add_sep: ${peft.model.data.train_ds.add_sep}
      add_bos: ${peft.model.data.train_ds.add_bos}
      write_predictions_to_file: False
      output_file_path_prefix: null # Prefix of the file to write predictions to.
      truncation_field: ${peft.model.data.train_ds.truncation_field} # Options: keys in prompt_template
      index_mapping_dir: null # Path to a directory to write index mapping files.
      prompt_template: ${peft.model.data.train_ds.prompt_template}
      tokens_to_generate: 32 # decide how many tokens we want to generate to evaluate performance with string metrics
      truncation_method: 'right' # Truncation from which position, Options: ['left', 'right']
      metric:
        name: "loss" # Name of the evaluation metric to use. Options: ['exact_string_match', 'loss']
        average: null # Average the metric over the dataset. Options: ['macro', 'micro']. Works only for 'F1', 'accuracy' etc. Refer to torchmetrics for metrics where this is supported.
        num_classes: null

  optim:
    name: distributed_fused_adam
    lr: 1e-4
    weight_decay: 0.01
    betas:
    - 0.9
    - 0.98
    bucket_cap_mb: 50
    dtype: bf16 # fp32 | bf16
    grad_sync_dtype: bf16 # fp32 | bf16
    overlap_grad_sync: True
    overlap_param_sync: True
    contiguous_grad_buffer: True
    contiguous_param_buffer: True

