run:
  name: DreamFusion_dmtet
  results_dir: ${base_results_dir}/${.name}
  time_limit: "2-00:00:00"
  dependency: "singleton"

defaults:
  - nerf/model: dreamfusion-dmtet
  - _self_

name: DreamFusion-train
seed: 2023
mode: fit

# export-mesh options
mesh_fname: /results/mesh.obj # mesh file name when mode=export-mesh
mesh_resolution: 128          # Mesh resolution when mode=export-mesh

# benchmark options
enable_benchmark: False
benchmark_callback:
  _target_: benchmark_callback.BenchmarkCallback
  log_every_n_steps: 1

trainer:
  devices: 1
  num_nodes: 1
  precision: 16
  max_steps: 10000 # example configs: dreamfuions=10000, dmtet=5000
  accelerator: gpu
  enable_checkpointing: False
  logger: False
  log_every_n_steps: 1
  val_check_interval: 100
  accumulate_grad_batches: 1
  benchmark: False
  enable_model_summary: True

exp_manager:
  name: nemo_dreamfusion
  explicit_log_dir: ${training.run.results_dir}/results
  create_tensorboard_logger: False
  create_wandb_logger: False
  wandb_logger_kwargs:
    project: dreamfusion
    group: nemo-df
    name: nemo_dreamfusion
    resume: True
  exp_dir: null
  create_checkpoint_callback: True
  checkpoint_callback_params:
    every_n_epochs: 0
    every_n_train_steps: 1000
    monitor: loss
    filename: 'nemo-dreamfusion-{step}'
    save_top_k: -1
    always_save_nemo: False
  resume_if_exists: True
  resume_ignore_no_checkpoint: True
