_target_: nemo.collections.multimodal.modules.nerf.background.tcnn_background.TCNNBackground
bound: 1
encoder_num_input_dims: 3   # 3 directions
encoder_cfg:
  otype: "HashGrid"
  n_levels: 16
  n_features_per_level: 2
  log2_hashmap_size: 19
  base_resolution: 16
  interpolation: "Smoothstep"
  per_level_scale: # default is np.exp2(np.log2(2048 * bound / 16) / (16 - 1))

background_net_num_output_dims: 3 # rgb
background_net_cfg:
  otype: "FullyFusedMLP"
  activation: "ReLU"
  output_activation: "None"
  n_neurons: 32
  n_hidden_layers: 2
