hydra:
  searchpath:
    - file:///opt/NeMo/examples/nlp/language_modeling/conf

run:
  name: gpt_40b_improved
  results_dir: ${base_results_dir}/${.name}
  time_limit: "1-00:00:00"
  dependency: "singleton"

trainer:
  num_nodes: 96
  devices: 8
  accelerator: gpu
  precision: bf16
  logger: False # logger provided by exp_manager
  enable_checkpointing: False
  use_distributed_sampler: False
  max_epochs: null
  max_steps: 100000 # consumed_samples = global_step * global_batch_size
  max_time: "6:11:00:00" # days:hours:minutes:seconds
  log_every_n_steps: 10
  val_check_interval: 2000
  limit_val_batches: 20
  limit_test_batches: 20
  accumulate_grad_batches: 1
  gradient_clip_val: 1.0

exp_manager:
  explicit_log_dir: ${training.run.results_dir}/results
  exp_dir: null
  name: megatron_gpt
  create_wandb_logger: False
  wandb_logger_kwargs:
    project: nemo_gpt3
    name: ${training.run.name}
  resume_if_exists: True
  resume_ignore_no_checkpoint: True
  create_checkpoint_callback: True
  checkpoint_callback_params:
    monitor: val_loss
    save_top_k: 5
    mode: min
    always_save_nemo: False # saves nemo file during validation, not implemented for model parallel
    save_nemo_on_train_end: False # not recommended when training large models on clusters with short time limits
    filename: 'megatron_gpt--{val_loss:.2f}-{step}-{consumed_samples}'
    model_parallel_size: ${multiply:${training.model.tensor_model_parallel_size}, ${training.model.pipeline_model_parallel_size}}
  log_step_timing: True
  step_timing_kwargs:
    sync_cuda: True
    buffer_size: 5

model:
  micro_batch_size: 1
  global_batch_size: 1536
  rampup_batch_size: null
  tensor_model_parallel_size: 8
  pipeline_model_parallel_size: 2
  virtual_pipeline_model_parallel_size: null
  encoder_seq_length: 2048
  max_position_embeddings: 2048
  num_layers: 48
  hidden_size: 8192
  ffn_hidden_size: 21824
  num_attention_heads: 64
  init_method_std: 0.007
  use_scaled_init_method: true
  hidden_dropout: 0.0
  attention_dropout: 0.0
  ffn_dropout: 0.0
  kv_channels: null
  apply_query_key_layer_scaling: true
  normalization: LayerNorm
  layernorm_zero_centered_gamma: True
  layernorm_epsilon: 1.0e-05
  do_layer_norm_weight_decay: false
  make_vocab_size_divisible_by: 128
  pre_process: true
  post_process: true
  persist_layer_norm: true
  bias: false
  activation: fast-swiglu
  headscale: false
  transformer_block_type: pre_ln
  openai_gelu: false
  normalize_attention_scores: true
  position_embedding_type: rope
  rotary_percentage: 0.5
  attention_type: multihead
  share_embeddings_and_output_weights: false
  tokenizer:
    library: 'megatron'
    type: 'GPT2BPETokenizer'
    model: null
    delimiter: null # only used for tabular tokenizer
    vocab_file: ${data_dir}/bpe/vocab.json
    merge_file: ${data_dir}/bpe/merges.txt
  native_amp_init_scale: 4294967296
  native_amp_growth_interval: 1000
  hysteresis: 2
  fp32_residual_connection: false
  fp16_lm_cross_entropy: false
  megatron_amp_O2: true
  grad_allreduce_chunk_size_mb: 125
  grad_div_ar_fusion: true
  gradient_accumulation_fusion: false
  bias_activation_fusion: false
  bias_dropout_add_fusion: false
  masked_softmax_fusion: true
  seed: 1234
  resume_from_checkpoint: null
  use_cpu_initialization: false
  onnx_safe: false
  apex_transformer_log_level: 30
  gradient_as_bucket_view: true
  sync_batch_comm: false
  activations_checkpoint_granularity: null
  activations_checkpoint_method: null
  activations_checkpoint_num_layers: null
  num_micro_batches_with_partial_activation_checkpoints: null
  activations_checkpoint_layers_per_pipeline: null
  sequence_parallel: false # does not support sequence parallel
  
  overlap_p2p_comm: False # Overlap p2p communication with computes. This argument is valid only when `virtual_pipeline_model_parallel_size` is larger than 1
  batch_p2p_comm: True # Batch consecutive inter-peer send/recv operations. This argument is valid only when `virtual_pipeline_model_parallel_size` is larger than 1
  num_query_groups: null # Number of query groups for group query attention. If None, normal attention is used.
  
  ## Using Megatron Core
  mcore_gpt: True

  ## Transformer Engine
  # fp8 training is currently not supported in the improved models
  transformer_engine: False
  fp8: False # enables fp8 in TransformerLayer forward
  fp8_e4m3: False # sets fp8_format = recipe.Format.E4M3
  fp8_hybrid: True # sets fp8_format = recipe.Format.HYBRID
  fp8_margin: 0 # scaling margin
  fp8_interval: 1 # scaling update interval
  fp8_amax_history_len: 1024 # Number of steps for which amax history is recorded per tensor
  fp8_amax_compute_algo: max # 'most_recent' or 'max'. Algorithm for computing amax from history
  fp8_wgrad: True
  use_emha: False
  ub_tp_comm_overlap: False

  optim:
    name: fused_adam
    lr: 9e-5
    weight_decay: 0.1
    betas:
      - 0.9
      - 0.95
    sched:
      name: CosineAnnealing
      warmup_steps: 500
      constant_steps: 0
      min_lr: 9e-5
  data:
    data_impl: mmap
    splits_string: "99990,8,2"
    seq_length: 2048
    skip_warmup: true
    num_workers: 2
    dataloader_type: single
    reset_position_ids: false
    reset_attention_mask: false
    eod_mask_loss: false
    index_mapping_dir: null
    data_prefix:
      - .0333
      - ${data_dir}/my-gpt3_00_text_document
      - .0333
      - ${data_dir}/my-gpt3_01_text_document
      - .0333
      - ${data_dir}/my-gpt3_02_text_document
      - .0333
      - ${data_dir}/my-gpt3_03_text_document
      - .0333
      - ${data_dir}/my-gpt3_04_text_document
      - .0333
      - ${data_dir}/my-gpt3_05_text_document
      - .0333
      - ${data_dir}/my-gpt3_06_text_document
      - .0333
      - ${data_dir}/my-gpt3_07_text_document
      - .0333
      - ${data_dir}/my-gpt3_08_text_document
      - .0333
      - ${data_dir}/my-gpt3_09_text_document
      - .0333
      - ${data_dir}/my-gpt3_10_text_document
      - .0333
      - ${data_dir}/my-gpt3_11_text_document
      - .0333
      - ${data_dir}/my-gpt3_12_text_document
      - .0333
      - ${data_dir}/my-gpt3_13_text_document
      - .0333
      - ${data_dir}/my-gpt3_14_text_document
      - .0333
      - ${data_dir}/my-gpt3_15_text_document
      - .0333
      - ${data_dir}/my-gpt3_16_text_document
      - .0333
      - ${data_dir}/my-gpt3_17_text_document
      - .0333
      - ${data_dir}/my-gpt3_18_text_document
      - .0333
      - ${data_dir}/my-gpt3_19_text_document
      - .0333
      - ${data_dir}/my-gpt3_20_text_document
      - .0333
      - ${data_dir}/my-gpt3_21_text_document
      - .0333
      - ${data_dir}/my-gpt3_22_text_document
      - .0333
      - ${data_dir}/my-gpt3_23_text_document
      - .0333
      - ${data_dir}/my-gpt3_24_text_document
      - .0333
      - ${data_dir}/my-gpt3_25_text_document
      - .0333
      - ${data_dir}/my-gpt3_26_text_document
      - .0333
      - ${data_dir}/my-gpt3_27_text_document
      - .0333
      - ${data_dir}/my-gpt3_28_text_document
      - .0334
      - ${data_dir}/my-gpt3_29_text_document
