run:
  name: ${.task_name}_${.model_train_name}
  time_limit: null
  dependency: "singleton"
  convert_name: convert_nemo
  model_train_name: gpt3_llama2_7b_steerlm_ac_reg
  convert_dir: ${base_results_dir}/${steerlm_reg.run.model_train_name}/${steerlm_reg.run.convert_name}
  task_name: "attribute_conditioned_sft"  # Rename this name to be more clear
  results_dir: ${base_results_dir}/${steerlm_reg.run.model_train_name}/${steerlm_reg.run.task_name}

trainer:
  num_nodes: 1
  devices: 8
  accelerator: gpu
  precision: bf16

  sft:
    max_epochs: 1
    max_steps: 100

    val_check_interval: 100
    save_interval: ${.val_check_interval}

    limit_val_batches: 1.0
    gradient_clip_val: 1.0

  # do not change these
  logger: False # logger provided by exp_manager
  enable_checkpointing: False
  use_distributed_sampler: False
  max_time: null
  max_epochs: 1
  max_steps: 100 #${.sft.max_steps}

exp_manager:
  explicit_log_dir: ${base_results_dir}/results/logs
  exp_dir: ${base_results_dir}/results/exp
  name: "steerlm_ac_sft" #${name}
  create_wandb_logger: False
  wandb_logger_kwargs:
    project: null
    name: null
  resume_if_exists: True
  resume_ignore_no_checkpoint: True
  create_checkpoint_callback: True
  checkpoint_callback_params:
    monitor: val_loss
    save_top_k: 1
    mode: min
    save_nemo_on_train_end: True 
    filename: 'steerlm_gpt_sft'
    model_parallel_size: 8 #${model.tensor_model_parallel_size}
    save_best_model: True  # need to keep this false otherwise it will create multiple last.ckpt files because restore reset the previous best model

model:
  steerlm:
  steerable_attributes :       
    quality: 4
    toxicity: 0
    humor: 0
    creativity: 0
    helpfulness: 4
    correctness: 4 
    coherence: 4
    complexity: 
    verbosity: 4
  seed: 1234
  tensor_model_parallel_size: 8 # intra-layer model parallelism
  pipeline_model_parallel_size: 1 # inter-layer model parallelism
  restore_from_path: ${data_dir}/ckpt/llama7b.nemo # Path to an existing .nemo model converted from HuggingFace, change the name to the ckpt accordingly
  resume_from_checkpoint: null # The path to a checkpoint file to continue the training, restores the whole state including the epoch, step, LR schedulers, apex, etc.
  save_nemo_on_validation_end: True # Saves an inference ready .nemo file every time a checkpoint is saved during training. 
  sync_batch_comm: False
  megatron_amp_O2: True
  encoder_seq_length: 4096  # the sequence length of the encoder model, it will be overwriten by loaded GPT model

  ## Sequence Parallelism
  # Makes tensor parallelism more memory efficient for LLMs (20B+) by parallelizing layer norms and dropout sequentially
  # See Reducing Activation Recomputation in Large Transformer Models: https://arxiv.org/abs/2205.05198 for more details.
  sequence_parallel: False

  ## Activation Checkpoint 
  activations_checkpoint_granularity: "selective" # 'selective' or 'full' 
  activations_checkpoint_method: "uniform" # 'uniform', 'block', not used with 'selective'
  # 'uniform' divides the total number of transformer layers and checkpoints the input activation
  # of each chunk at the specified granularity
  # 'block' checkpoints the specified number of layers per pipeline stage at the specified granularity
  activations_checkpoint_num_layers: null # not used with 'selective'
  activations_checkpoint_layers_per_pipeline: null
  # This feature is valid only when used with pipeline-model-parallelism. More details in megatron_gpt_config.yaml.
  answer_only_loss: False # not used right now
  gradient_as_bucket_view: False
  seq_len_interpolation_factor: null # if not None, seq_len_interpolation_factor will match the base model's value
  use_flash_attention: null # if not None, will match the base model's value

  hidden_dropout: 0.0
  attention_dropout: 0.0
  ffn_dropout: 0.0

  data:
    chat: True # whether use chatbot data or not
    chat_prompt_tokens:  # special tokens for the chat prompts, a dictionary of {token_type: token}. note that some tokenizer may combine the characters at the junction between {end_of_turn}{turn_start}. e.g. '<im end><im start>', the '><' sometimes is merged to be a single token. This is not supported, try to avoid
      system_turn_start: \'\<extra_id_0\>\'
      turn_start: \'\<extra_id_1\>\'
      label_start: \'\<extra_id_2\>\'
      end_of_turn: "\x0A"  # \0x0A is '\n'
      end_of_name: "\x0A"  # \0x0A is '\n'
    sample: False # create the index mapping files for the sample data, so max_steps * global_batch_size can be larger than the dataset size
    num_workers: 1
    dataloader_type: single  # only supports single
    train_ds:
      # Example of how to specify paths to multiple datasets
      # file_names:
      #   - /path/to/squad.jsonl
      #   - /path/to/mnli.jsonl
      #   - /path/to/boolq.jsonl
      # Example of how each dataset is formatted
      # {'input': 'John von Neumann\nVon Neumann made fundamental contributions .... Q: What did the math of artificial viscosity do?', 'output': 'smoothed the shock transition without sacrificing basic physics'}
      file_path: ??? # Path to a JSONL file corresponding to the source data. Data format is identical to validation_ds.
      global_batch_size: 128
      micro_batch_size: 1
      shuffle: True
      memmap_workers: null
      max_seq_length: 2048
      min_seq_length: 1
      drop_last: True  # note that `False` is not currently supported
      # Example of how to specify concat_sampling_probabilities
      # concat_sampling_probabilities:
      #   - 0.5
      #   - 0.25
      #   - 0.25
      label_key: 'output'
      add_eos: True
      add_sep: False
      add_bos: False
      truncation_field: "input" # # Can be multiple keys separated with ',' Options: keys in prompt_template
      index_mapping_dir: null # Path to a directory to write index mapping files.
      prompt_template: "{input} {output}" # fstring to use for assistant prompt. Example: "Q: {input}\nA: {output}"
      hf_dataset: False # Whether to load the json file with the HuggingFace dataset. otherwise, will load the jsonl file with the JSONLMemMapDataset.
      truncation_method: 'right' # Truncation from which position, Options: ['left', 'right']

    validation_ds:
      file_path: ${data_dir}/data/oasst/val_labeled.jsonl # Path to a JSONL file corresponding to the source data. Data format is identical to validation_ds.
      names: null # Names of the corresponding datasets used to log metrics.
      global_batch_size: 128 #${model.data.train_ds.global_batch_size}
      micro_batch_size: 1 #${model.data.train_ds.micro_batch_size}
      shuffle: False
      memmap_workers: null #${model.data.train_ds.memmap_workers}
      max_seq_length: 2048 #${model.data.train_ds.max_seq_length}
      min_seq_length: 1
      drop_last: False
      label_key: 'output' #${model.data.train_ds.label_key}
      add_eos: False #${model.data.train_ds.add_eos}
      add_sep: False #${model.data.train_ds.add_sep}
      add_bos: False #${model.data.train_ds.add_bos}
      write_predictions_to_file: False
      output_file_path_prefix: null # Prefix of the file to write predictions to.
      truncation_field: "input" #${model.data.train_ds.truncation_field} # Options: keys in prompt_template
      index_mapping_dir: null # Path to a directory to write index mapping files.
      prompt_template: "{input} {output}" #${model.data.train_ds.prompt_template} # fstring to use for assistant prompt. Example: "Q: {input}\nA: {output}"
      tokens_to_generate: 32 # decide how many tokens we want to generate to evaluate performance with string metrics
      hf_dataset: False # Whether to load the json file with the HuggingFace dataset. otherwise, will load the jsonl file with the JSONLMemMapDataset.
      truncation_method: 'right' # Truncation from which position, Options: ['left', 'right'] 

      metric:
        name: "loss" # Name of the evaluation metric to use. Options: ['exact_string_match', 'loss', 'rouge', 'token_f1']
        average: null # Average the metric over the dataset. Options: ['macro', 'micro']. Works only for 'F1', 'accuracy' etc. Refer to torchmetrics for metrics where this is supported.
        num_classes: null

    test_ds:
      prompt_template: "{input} {output}" #${model.data.train_ds.prompt_template} # fstring to use for assistant prompt. Example: "Q: {input}\nA: {output}"

  optim:
    name: distributed_fused_adam # Supports distributed optimizer for memory savings. To enable, set to 'distributed_fused_adam'. Needs Apex to be built with specific args to work.
    lr: 3e-5
    weight_decay: 0.01 
    betas: 
    - 0.9
    - 0.98
    sched:
      name: CosineAnnealing
      warmup_steps: 10
      constant_steps: 1000
      min_lr: 9e-7

inference:
  greedy: True # Whether or not to use sampling ; use greedy decoding otherwise
  top_k: 0  # The number of highest probability vocabulary tokens to keep for top-k-filtering.
  top_p: 0.9 # If set to float < 1, only the most probable tokens with probabilities that add up to top_p or higher are kept for generation.
  temperature: 1.0 # sampling temperature
  all_probs: False  # whether return the log prob for all the tokens in vocab
  repetition_penalty: 1.2  # The parameter for repetition penalty. 1.0 means no penalty.
  min_tokens_to_generate: 0  # The minimum length of the sequence to be generated.
  compute_logprob: False  # a flag used to compute logprob of all the input text, a very special case of running inference, default False
  compute_attention_mask: True
