defaults:
  - _self_
  - optional tp_overlap@model.ub_tp_comm_overlap_cfg: ub_cfg_h100_h8192_tp4_mbs1_seqlen4096

hydra:
  searchpath:
    - file:///opt/NeMo/examples/nlp/language_modeling/conf

run:
  name: qwen2_72b
  results_dir: ${base_results_dir}/${.name}
  time_limit: 0-01:00:00
  dependency: singleton
trainer:
  num_nodes: 128
  devices: 8
  accelerator: gpu
  precision: bf16
  logger: false
  enable_checkpointing: false
  use_distributed_sampler: False
  max_epochs: null
  max_steps: 300000
  max_time: '19:23:30:00'
  log_every_n_steps: 10
  val_check_interval: 2000
  limit_val_batches: 32
  limit_test_batches: 50
  accumulate_grad_batches: 1
  gradient_clip_val: 1.0
exp_manager:
  explicit_log_dir: ${training.run.results_dir}/results
  exp_dir: null
  name: megatron_qwen2
  create_wandb_logger: false
  wandb_logger_kwargs:
    project: nemo_qwen2_pretrain
    name: ${training.run.name}
  resume_if_exists: false
  resume_ignore_no_checkpoint: true
  create_checkpoint_callback: True
  checkpoint_callback_params:
    monitor: val_loss
    save_top_k: 10
    mode: min
    always_save_nemo: false
    save_nemo_on_train_end: true
    filename: megatron_qwen2--{val_loss:.2f}-{step}-{consumed_samples}
    model_parallel_size: ${multiply:${training.model.tensor_model_parallel_size}, ${training.model.pipeline_model_parallel_size}}
  log_step_timing: true
  step_timing_kwargs:
    sync_cuda: true
    buffer_size: 5
model:
  mcore_gpt: true
  micro_batch_size: 1
  global_batch_size: 2048
  rampup_batch_size: null
  tensor_model_parallel_size: 4
  pipeline_model_parallel_size: 4
  virtual_pipeline_model_parallel_size: 20
  encoder_seq_length: 32768
  max_position_embeddings: 32768
  num_layers: 80
  hidden_size: 8192
  ffn_hidden_size: 24576
  num_attention_heads: 64
  num_query_groups: 64
  override_vocab_size: 152064
  rotary_base: 1000000.0
  init_method_std: 0.02
  use_scaled_init_method: true
  hidden_dropout: 0.0
  attention_dropout: 0.0
  ffn_dropout: 0.0
  kv_channels: null
  apply_query_key_layer_scaling: true
  normalization: rmsnorm
  layernorm_epsilon: 1.0e-05
  do_layer_norm_weight_decay: false
  make_vocab_size_divisible_by: 128
  pre_process: true
  post_process: true
  persist_layer_norm: true
  bias: false
  qkv_bias: true
  activation: fast-swiglu
  headscale: false
  transformer_block_type: pre_ln
  openai_gelu: false
  normalize_attention_scores: true
  position_embedding_type: rope
  rotary_percentage: 1.0
  apply_rope_fusion: true
  attention_type: multihead
  share_embeddings_and_output_weights: false
  tokenizer:
    library: 'huggingface'
    type: Qwen/Qwen1.5-72B
    model: null # /path/to/tokenizer.model
    delimiter: null
    vocab_file: null
    merge_file: null
    sentencepiece_legacy: false
  native_amp_init_scale: 4294967296
  native_amp_growth_interval: 1000
  hysteresis: 2
  fp32_residual_connection: false
  fp16_lm_cross_entropy: false
  megatron_amp_O2: true
  grad_allreduce_chunk_size_mb: 125
  grad_div_ar_fusion: true
  gradient_accumulation_fusion: true
  bias_activation_fusion: false
  bias_dropout_add_fusion: false
  masked_softmax_fusion: true
  seed: 1234
  resume_from_checkpoint: null
  use_cpu_initialization: false
  onnx_safe: false
  apex_transformer_log_level: 30
  gradient_as_bucket_view: true
  sync_batch_comm: false
  activations_checkpoint_granularity: null
  activations_checkpoint_method: block
  activations_checkpoint_num_layers: 0
  num_micro_batches_with_partial_activation_checkpoints: 0
  activations_checkpoint_layers_per_pipeline: 0
  sequence_parallel: true
  transformer_engine: true
  fp8: false
  fp8_e4m3: false
  fp8_hybrid: false
  fp8_margin: 0
  fp8_interval: 1
  fp8_amax_history_len: 1
  fp8_amax_compute_algo: most_recent
  use_emha: false
  ub_tp_comm_overlap: true
  tp_comm_atomic_ag: False
  tp_comm_atomic_rs: False
  use_flash_attention: true
  overlap_p2p_comm: true
  batch_p2p_comm: false
  gc_interval: 3
  optim:
    name: distributed_fused_adam
    lr: 0.00015
    weight_decay: 0.1
    betas:
    - 0.9
    - 0.95
    bucket_cap_mb: 125
    overlap_grad_sync: true
    overlap_param_sync: true
    contiguous_grad_buffer: true
    sched:
      name: CosineAnnealing
      warmup_steps: 2000
      constant_steps: 11873
      min_lr: 1.0e-05
  data:
    data_impl: mmap
    splits_string: 99990,8,2
    seq_length: 32768
    skip_warmup: true
    num_workers: 2
    dataloader_type: single
    reset_position_ids: false
    reset_attention_mask: false
    eod_mask_loss: false
    index_mapping_dir: null
    data_prefix:
    - .0333
    - ${data_dir}/my-qwen2_00_text_document
    - .0333
    - ${data_dir}/my-qwen2_01_text_document
    - .0333
    - ${data_dir}/my-qwen2_02_text_document
    - .0333
    - ${data_dir}/my-qwen2_03_text_document
    - .0333
    - ${data_dir}/my-qwen2_04_text_document
    - .0333
    - ${data_dir}/my-qwen2_05_text_document
    - .0333
    - ${data_dir}/my-qwen2_06_text_document
    - .0333
    - ${data_dir}/my-qwen2_07_text_document
    - .0333
    - ${data_dir}/my-qwen2_08_text_document
    - .0333
    - ${data_dir}/my-qwen2_09_text_document
    - .0333
    - ${data_dir}/my-qwen2_10_text_document
    - .0333
    - ${data_dir}/my-qwen2_11_text_document
    - .0333
    - ${data_dir}/my-qwen2_12_text_document
    - .0333
    - ${data_dir}/my-qwen2_13_text_document
    - .0333
    - ${data_dir}/my-qwen2_14_text_document
    - .0333
    - ${data_dir}/my-qwen2_15_text_document
    - .0333
    - ${data_dir}/my-qwen2_16_text_document
    - .0333
    - ${data_dir}/my-qwen2_17_text_document
    - .0333
    - ${data_dir}/my-qwen2_18_text_document
    - .0333
    - ${data_dir}/my-qwen2_19_text_document
    - .0333
    - ${data_dir}/my-qwen2_20_text_document
    - .0333
    - ${data_dir}/my-qwen2_21_text_document
    - .0333
    - ${data_dir}/my-qwen2_22_text_document
    - .0333
    - ${data_dir}/my-qwen2_23_text_document
    - .0333
    - ${data_dir}/my-qwen2_24_text_document
    - .0333
    - ${data_dir}/my-qwen2_25_text_document
    - .0333
    - ${data_dir}/my-qwen2_26_text_document
    - .0333
    - ${data_dir}/my-qwen2_27_text_document
    - .0333
    - ${data_dir}/my-qwen2_28_text_document
    - .0334
    - ${data_dir}/my-qwen2_29_text_document

