name: "neva"
backend: "python"

model_transaction_policy {
  decoupled: True
}

input [
    {
        name: "prompt"
        data_type: TYPE_STRING
        dims: [ 1 ]
    },
    {
        name: "images"
        data_type: TYPE_STRING
        dims: [ -1 ]
    },
    {
        name: "stop"
        data_type: TYPE_STRING
        dims: [ 1 ]
    },
    {
        name: "max_new_tokens"
        data_type: TYPE_UINT16
        dims: [ 1 ]
    },
    {
        name: "temperature"
        data_type: TYPE_FP32
        dims: [ 1 ]
        optional: true
    },
    {
        name: "random_seed"
        data_type: TYPE_UINT32
        dims: [ 1 ]
        optional: true
    }
]

output [
    {
        name: "generated_text"
        data_type: TYPE_STRING
        dims: [ 1 ]
    }
]

instance_group [
    {
        count: 1
        kind: KIND_MODEL
    }
]
