run:
  name: fw_inference_${.model_train_name}
  time_limit: "04:00:00"
  dependency: "singleton"
  model_train_name: dreambooth_sd_860m
  results_dir: ${base_results_dir}/${.model_train_name}/${.name}

infer:
  unconditional_guidance_scale: 7.5
  num_images_per_prompt: 4
  batch_size: 4
  height: 512
  width: 512
  down_factor: 8
  inference_steps: 100
  sampler_type: 'DDIM'
  eta: 0
  output_type: 'pil'
  save_to_file: True
  out_path: ${fw_inference.run.results_dir}
  seed: 234
  prompts:
    - "a photo of a sks dog"
    - "a photo of a sks dog in the Acropolis"
    - "a photo of a sks dog in front of eiffel tower"
    - "a photo of sks dog sleeping"
    - "a photo of a sks dog riding a bike"

trainer:
  devices: 1
  num_nodes: 1
  accelerator: gpu
  precision: 16
  logger: False # logger provided by exp_manager

model:
  restore_from_path: ${base_results_dir}/${fw_inference.run.model_train_name}/convert_nemo/results/nemo_dreambooth.nemo  # Path to a trained CLIP .nemo file
  precision: ${fw_inference.trainer.precision}
