run:
  name: ${.task_name}_${.model_train_name}
  time_limit: null
  dependency: "singleton"
  convert_name: convert_nemo
  model_train_name: gpt3_llama2_7b_steerlm_reg
  convert_dir: ${base_results_dir}/${steerlm_reg.run.model_train_name}/${steerlm_reg.run.convert_name}
  task_name: "oasst"  # Rename this name to be more clear
  results_dir: ${base_results_dir}/${steerlm_reg.run.model_train_name}/${steerlm_reg.run.task_name}
trainer:
  num_nodes: 1
  devices: 8
  accelerator: gpu
  precision: bf16

  # rm specific args
  rm:
    max_epochs: 1
    max_steps: 100
    val_check_interval: 100
    save_interval: 100

    # how many GBS we loop over
    # set to float for a percentage
    # of the validation dataset
    limit_val_batches: 1.0
    gradient_clip_val: 1.0

  # do not change these
  logger: False # logger provided by exp_manager
  enable_checkpointing: False
  use_distributed_sampler: False
  max_time: null #04:00:00
  max_epochs: 1 #${.rm.max_epochs}
  max_steps: 100 #${.rm.max_steps}

exp_manager:
  explicit_log_dir: ${base_results_dir}/results
  exp_dir: null
  name: megatron_gpt
  max_time_per_run: null #04:00:00 #${trainer.max_time}
  create_wandb_logger: False
  wandb_logger_kwargs:
    project: nemo_aligner_rm
    name: steerlm_reg_gpt3_rm
  resume_from_checkpoint: null # The path to a checkpoint file to continue the training, restores the whole state including the epoch, step, LR schedulers, apex, etc.
  resume_if_exists: True
  resume_ignore_no_checkpoint: True
  create_checkpoint_callback: True
  checkpoint_callback_params:
    monitor: val_loss
    save_top_k: 1
    mode: min
    always_save_nemo: False # saves nemo file during validation, not implemented for model parallel
    save_nemo_on_train_end: True # not recommended when training large models on clusters with short time limits
    filename: 'megatron_gpt--{val_loss:.3f}-{step}-{consumed_samples}-{epoch}'
    model_parallel_size: ${multiply:${steerlm_reg.model.tensor_model_parallel_size}, ${steerlm_reg.model.pipeline_model_parallel_size}}

pretrained_checkpoint:
  restore_from_path: ${data_dir}/ckpt/llama7b.nemo

model:
  mcore_gpt: True
  share_embeddings_and_output_weights: False
  tensor_model_parallel_size: 8
  pipeline_model_parallel_size: 1
  activations_checkpoint_granularity : "selective"
  activations_checkpoint_method: "uniform"

  reward_model_type: regression #binary_ranking # ["binary_ranking, "regression"]
  regression:
    num_attributes: 9 # dimension of regression head
    merge_attributes: False # whether to merge multiple attributes into a scalar
    attribute_weights: null # apply these weights to each attributes when merging them into a scalar
    loss_mask_val: -100 #  mask dimensions with this value when calculating MSE loss
  output_sequence: False  # Whether to output a single scalar or a sequence of scalars.
  use_avg_pool: False  # Whether to use avg pool to sum across the sequence dim in reward model
  force_head_dtype: float32  # enforce specific dtype for the final projection in the model head
  micro_batch_size: 2
  global_batch_size: 16
  megatron_amp_O2: True

  encoder_seq_length: 4096
  max_position_embeddings: 4096 #${steerlm_reg.model.encoder_seq_length}

  # miscellaneous
  seed: 1234

  optim:
    name: mcore_distributed_optim
    bucket_cap_mb: 200
    overlap_grad_sync: False
    contiguous_grad_buffer: True
    lr: 9e-6
    weight_decay: 0.1
    betas:
    - 0.9
    - 0.98
    sched:
      name: CosineAnnealing
      warmup_steps: 10
      constant_steps: 0
      min_lr: 9e-7

  data:
    data_impl: jsonl
    splits_string: null
    seq_length: 4096 #${steerlm_reg.model.encoder_seq_length}
    skip_warmup: True
    num_workers: 2
    dataloader_type: single # cyclic
    reset_position_ids: False # Reset position ids after end-of-document token
    reset_attention_mask: False # Reset attention mask after end-of-document token
    eod_mask_loss: False # Mask loss for the end of document tokens
    index_mapping_dir: null # path to save index mapping .npy files, by default will save in the same location as data_prefix
    data_prefix: {train: ["${data_dir}/data/merge_train_reg.jsonl"], validation: ["${data_dir}/data/merge_val_reg.jsonl"], test: ["${data_dir}/data/merge_val_reg.jsonl"]}

  precision: bf16 #${trainer.precision}