run:
  name: llama_7b
  results_dir: ${base_results_dir}/${.name}
  time_limit: "0-04:00:00"
  dependency: "singleton"
trainer:
  num_nodes: 16
  devices: 8
  accelerator: gpu
  precision: bf16
  logger: False # logger provided by exp_manager
  enable_checkpointing: False
  use_distributed_sampler: False
  max_epochs: null
  max_steps: 300000 # consumed_samples = global_step * global_batch_size
  max_time: "05:23:30:00" # days:hours:minutes:seconds
  log_every_n_steps: 10
  val_check_interval: 2000
  limit_val_batches: 32
  limit_test_batches: 50
  accumulate_grad_batches: 1
  gradient_clip_val: 1.0
exp_manager:
  explicit_log_dir: ${training.run.results_dir}/results
  exp_dir: null
  name: megatron_llama
  create_wandb_logger: false
  wandb_logger_kwargs:
    project: nemo_llama
    name: ${training.run.name}
  resume_if_exists: True
  resume_ignore_no_checkpoint: True
  create_checkpoint_callback: True
  checkpoint_callback_params:
    monitor: val_loss
    save_top_k: 10
    mode: min
    always_save_nemo: False # saves nemo file during validation, not implemented for model parallel
    save_nemo_on_train_end: False # not recommended when training large models on clusters with short time limits
    filename: 'megatron_llama--{val_loss:.2f}-{step}-{consumed_samples}'
    model_parallel_size: ${multiply:${training.model.tensor_model_parallel_size}, ${training.model.pipeline_model_parallel_size}}
  log_step_timing: True
  step_timing_kwargs:
    sync_cuda: True
    buffer_size: 5

model:
  mcore_gpt: true
  micro_batch_size: 2
  global_batch_size: 2048
  rampup_batch_size: null
  tensor_model_parallel_size: 1
  pipeline_model_parallel_size: 1
  virtual_pipeline_model_parallel_size: null
  encoder_seq_length: 2048
  max_position_embeddings: 2048
  num_layers: 32
  hidden_size: 4096
  ffn_hidden_size: 11008
  num_attention_heads: 32
  init_method_std: 0.01
  use_scaled_init_method: true
  hidden_dropout: 0.0
  attention_dropout: 0.0
  ffn_dropout: 0.0
  kv_channels: null
  apply_query_key_layer_scaling: true
  normalization: rmsnorm
  layernorm_epsilon: 1.0e-05
  do_layer_norm_weight_decay: false
  make_vocab_size_divisible_by: 128
  pre_process: true
  post_process: true
  persist_layer_norm: true
  bias: false
  activation: fast-swiglu
  headscale: false
  transformer_block_type: pre_ln
  openai_gelu: false
  normalize_attention_scores: true
  position_embedding_type: rope
  rotary_percentage: 1.0
  attention_type: multihead
  share_embeddings_and_output_weights: false
  tokenizer:
    library: 'sentencepiece'
    type: null
    model: ${data_dir}/llama/llama_tokenizer.model
    delimiter: null
    vocab_file: null
    merge_file: null
    sentencepiece_legacy: False
  native_amp_init_scale: 4294967296
  native_amp_growth_interval: 1000
  hysteresis: 2
  fp32_residual_connection: false
  fp16_lm_cross_entropy: false
  megatron_amp_O2: true
  grad_allreduce_chunk_size_mb: 125
  grad_div_ar_fusion: true
  gradient_accumulation_fusion: true
  bias_activation_fusion: false
  bias_dropout_add_fusion: false
  masked_softmax_fusion: true
  seed: 1234
  resume_from_checkpoint: null
  use_cpu_initialization: false
  onnx_safe: false
  apex_transformer_log_level: 30
  gradient_as_bucket_view: true
  sync_batch_comm: false
  activations_checkpoint_granularity: null
  activations_checkpoint_method: block
  activations_checkpoint_num_layers: 0
  num_micro_batches_with_partial_activation_checkpoints: null
  activations_checkpoint_layers_per_pipeline: null
  sequence_parallel: false # does not support sequence parallel

  ## Transformer Engine
  transformer_engine: True
  fp8: False # enables fp8 in TransformerLayer forward
  fp8_e4m3: False # sets fp8_format = recipe.Format.E4M3
  fp8_hybrid: False # sets fp8_format = recipe.Format.HYBRID
  fp8_margin: 0 # scaling margin
  fp8_interval: 1 # scaling update interval
  fp8_amax_history_len: 1024 # Number of steps for which amax history is recorded per tensor
  fp8_amax_compute_algo: max # 'most_recent' or 'max'. Algorithm for computing amax from history
  use_emha: False
  ub_tp_comm_overlap: False
  use_flash_attention: True
  optim:
    name: distributed_fused_adam
    lr: 1e-4
    weight_decay: 0.1
    betas:
      - 0.9
      - 0.95
    bucket_cap_mb: 125
    overlap_grad_sync: true
    overlap_param_sync: true
    contiguous_grad_buffer: true
    sched:
      name: CosineAnnealing
      warmup_steps: 500
      constant_steps: 0
      min_lr: 1e-5
  data:
    data_impl: mmap
    splits_string: "99990,8,2"
    seq_length: 2048
    skip_warmup: true
    num_workers: 2
    dataloader_type: single
    reset_position_ids: false
    reset_attention_mask: false
    eod_mask_loss: false
    index_mapping_dir: null
    data_prefix:
    - .0333
    - ${data_dir}/my-llama_00_text_document
    - .0333
    - ${data_dir}/my-llama_01_text_document
    - .0333
    - ${data_dir}/my-llama_02_text_document
    - .0333
    - ${data_dir}/my-llama_03_text_document
    - .0333
    - ${data_dir}/my-llama_04_text_document
    - .0333
    - ${data_dir}/my-llama_05_text_document
    - .0333
    - ${data_dir}/my-llama_06_text_document
    - .0333
    - ${data_dir}/my-llama_07_text_document
    - .0333
    - ${data_dir}/my-llama_08_text_document
    - .0333
    - ${data_dir}/my-llama_09_text_document
    - .0333
    - ${data_dir}/my-llama_10_text_document
    - .0333
    - ${data_dir}/my-llama_11_text_document
    - .0333
    - ${data_dir}/my-llama_12_text_document
    - .0333
    - ${data_dir}/my-llama_13_text_document
    - .0333
    - ${data_dir}/my-llama_14_text_document
    - .0333
    - ${data_dir}/my-llama_15_text_document
    - .0333
    - ${data_dir}/my-llama_16_text_document
    - .0333
    - ${data_dir}/my-llama_17_text_document
    - .0333
    - ${data_dir}/my-llama_18_text_document
    - .0333
    - ${data_dir}/my-llama_19_text_document
    - .0333
    - ${data_dir}/my-llama_20_text_document
    - .0333
    - ${data_dir}/my-llama_21_text_document
    - .0333
    - ${data_dir}/my-llama_22_text_document
    - .0333
    - ${data_dir}/my-llama_23_text_document
    - .0333
    - ${data_dir}/my-llama_24_text_document
    - .0333
    - ${data_dir}/my-llama_25_text_document
    - .0333
    - ${data_dir}/my-llama_26_text_document
    - .0333
    - ${data_dir}/my-llama_27_text_document
    - .0333
    - ${data_dir}/my-llama_28_text_document
    - .0334
    - ${data_dir}/my-llama_29_text_document

