_target_: nemo.collections.multimodal.modules.nerf.geometry.tcnn_nerf.TCNNNerf
num_input_dims: 3   # 3D space
bound: 1
density_activation: softplus # softplus, exp
blob_radius: 0.5
blob_density: 10
normal_type: central_finite_difference

encoder_cfg:
  otype: "HashGrid"
  n_levels: 16
  n_features_per_level: 2
  log2_hashmap_size: 19
  base_resolution: 16
  interpolation: "Smoothstep"
  per_level_scale: # default is np.exp2(np.log2(2048 * bound / 16) / (16 - 1))

sigma_net_num_output_dims: 1 # density
sigma_net_cfg:
  otype: "FullyFusedMLP"
  activation: "ReLU"
  output_activation: "None"
  n_neurons: 64
  n_hidden_layers: 3

features_net_num_output_dims: 3 # rgb
features_net_cfg:
  otype: "FullyFusedMLP"
  activation: "ReLU"
  output_activation: "None"
  n_neurons: 64
  n_hidden_layers: 3
