_target_: nemo_launcher.core.v2.config_k8s.K8sClusterConfig
volumes:
  workspace:
    # mount_path=null mirrors the volume into all the containers. Specify a different path if
    mount_path: null
    persistent_volume_claim:
      claim_name: nemo-workspace
  dshm:
    mount_path: /dev/shm
    empty_dir:
      medium: Memory
      # Amount of system memory to allocate in Pods. Should end in "Gi" for gigabytes.
      size_limit: 512Gi
namespace: null  # null implies to use current namespace

ib_interfaces:
  annotation: ""  # Specify the networks as comma separated values
  resources: {}
    # key: Specify the resource name for IB devices according to kubernetes, such as "nvidia.com/hostdev" for Mellanox IB adapters.
    # value: Specify the number of IB devices to include per node in each pod.
    # nvidia.com/hostdev: 8

dns_policy: null  # Specify a dnsPolicy to use in all pods, if necessary
pull_secret: ngc-registry  # Kubernetes secret for the container registry to pull private containers. Set to "null" if the imagePullSecret is managed by the scheduler or otherwise not needed.
custom_mpijob_api_version: null  # Optionally specify a custom k8s API version for MPIJobs. Default is "kubeflow.org/v1". This occurs when a cluster has different API versions installed.
custom_pytorchjob_api_version: null  # Optionally specify a custom k8s API version for PyTorchJobs. Default is "kubeflow.org/v1". This occurs when a cluster has different API versions installed.
scheduler: null  # Specify a custom kubernetes scheduler if different from default, such as "runai-scheduler". Leave as "null" if the default scheduler is desired.
service_account: null # Optionally specify a serviceAccountName to use while running jobs. Set to "null" if no serviceAccountName is desired.
capabilities: []
