name: launcher

on:
  pull_request:
    branches:
      - 'main'

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    env:
      working-directory: ./launcher_scripts

    steps:
      - name: checkout the repo
        uses: actions/checkout@v3

      - name: install dependencies
        run: |
          python -m pip install pytest requests-mock -r requirements.txt

      - name: run unit tests
        run: PYTHONPATH=$PWD pytest
        working-directory: ${{env.working-directory}}
