name: code_style

on:
  pull_request:
    branches:
      - 'master'

jobs:
  black:
    runs-on: ubuntu-latest
    env:
      working-directory: .

    steps:
      - name: checkout the repo
        uses: actions/checkout@v3

      - name: install dependencies
        run: pip install --upgrade black==19.10b0 click==8.0.2

      - name: code style check
        run: black . --check --verbose --diff
        working-directory: ${{env.working-directory}}