image:
  trainingImage: cfg.container
  pullPolicy: IfNotPresent

  # Insert the name of your container registry pull secret #
  pullSecret: nvcr.io

  numGPUs: training.trainer.devices
  nodes: training.trainer.num_nodes

trainingConfig:
  # Specify the amount of shared memory to attach to the Pods #
  shmSize: 512Gi

  # Insert the address for the NFS server if using NFS for model storage #
  NFSServer: <Insert NFS server address>

  # Insert the path to save data on the NFS server #
  NFSPath: <Insert NFS server path>

  # Specify the k8s resource name for IB devices. Can be string or list of strings. If list, must be same length as ibCount #
  ibResourceName: nvidia.com/hostdev

  # Specity the number of IB devices to include in pods. Can be string or list. If list, must be same length as ibResourceName #
  ibCount: "8"

  # Specity the number of IB networks to include in pods. Should be a comma separated set of networks. #
  ibNetworkAnnotation: ""

  # Specify the WandB API key if using WandB for logging #
  wandbKey: "nil"

  # Insert the dnsPolicy #
  dnsPolicy: "nil"
